services:
  cyclemap-backend-api:
    image: cyclemap/backend
    container_name: cyclemap-backend
    env_file: ./.env
    environment:
      - server.port=8989
      -  spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.datasource.url=jdbc:mysql://mysqldb:$MYSQLDB_PORT/$MYSQLDB_DB?useSSL=false&allowPublicKeyRetrieval=true
      - spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
      - spring.datasource.username=$MYSQLDB_USER
      - spring.datasource.password=$MYSQLDB_ROOT_PASS
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.generate-ddl=true
      - spring.security.user.name=$SPRING_SECURITY_USER
      - spring.security.user.password=$SPRING_SECURITY_PASS
      - CycleMap.allowedEndpoint=$CORS_ENDPOINT
    depends_on:
      - mysqldb
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    ports:
      - "8989:8989"
    restart: unless-stopped

  cyclemap-frontend:
    image: cyclemap/frontend
    container_name: cyclemap-frontend
    env_file: ./.env
    restart: unless-stopped
    ports:
      - "3001:80"
    depends_on:
      - cyclemap-backend-api
    build:
      context: .
      dockerfile: ./client/Dockerfile
      args:
       VUE_APP_BACKEND_API_URL: $BACKEND_ENDPOINT

  mysqldb:
    image: mysql:latest
    container_name: cyclemap-mysqldb
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASS
      - MYSQL_DATABASE=$MYSQLDB_DB
    ports:
      - $MYSQLDB_PORT:$MYSQLDB_PORT
    volumes:
      - ./db:/var/lib/mysql:rw,delegated
